name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

      - name: Deps install
        run: make install
      
      - name: Build project
        run: make build
        env:
          CI: true

      - name: Linter check
        run: make lint
      
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_ID }}
        with:
          coverageCommand: make test
          debug: true